# Generated by Django 6.1.1 on 2026-10-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Desierto, Naturaleza).', max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la región (ej: Valparaíso, Los Lagos).', max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'región',
                'verbose_name_plural': 'regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único usado en la URL.', max_length=100, unique=True, verbose_name='slug')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('mejor_epoca', models.CharField(blank=True, help_text='Época recomendada para visitar.', max_length=200, verbose_name='mejor época')),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa a static/ (ej: destinos/images/foto.jpg).', max_length=300, verbose_name='imagen')),
                ('destacado', models.BooleanField(default=False, help_text='¿Aparece en la sección destacados del inicio?', verbose_name='destacado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='destinos.categoria', verbose_name='categoría')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='destinos.region', verbose_name='región')),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'destinos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='destinos.destino', verbose_name='destino')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['nombre'],
            },
        ),
    ]
