# Generated by Django 6.1.1 on 2026-10-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único usado en la URL.', max_length=100, unique=True, verbose_name='slug')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('region', models.CharField(blank=True, help_text='Zona geográfica (ej: Todo Chile, Chiloé, Zona central).', max_length=100, verbose_name='región')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('historia', models.TextField(blank=True, verbose_name='historia')),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa a static/ (ej: gastronomia/images/foto.jpg).', max_length=300, verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'plato',
                'verbose_name_plural': 'platos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo (ej: Comida tradicional, Plato de fondo).', max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de plato',
                'verbose_name_plural': 'tipos de plato',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='gastronomia.plato', verbose_name='plato')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='plato',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='gastronomia.tipoplato', verbose_name='tipo'),
        ),
    ]
